 PyTorch Overview
Open-Source Deep Learning Library: Developed by Meta AI (formerly Facebook AI
Research).

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

# Scalars, vectors, matrices, and tensors. PyTorch tensors are similar to NumPy arrays

In [5]:
# using zeros
torch.zeros(2,3)
# using ones
torch.ones(2,3)
# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)
print(tensor0d)
# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d)
# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])
print(tensor2d)
# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(tensor3d)

tensor(1)
tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


# dimension and shape of matrices

In [6]:
scalar=torch.tensor(8)
print(scalar.ndim)  #to know the number of dimension  scalar have zero dimension dim= no of pointer required to access it 1d or 2d
vector=torch.tensor([3,4])  #ndim=1
print(vector.ndim)
vector=torch.tensor([[3,4],[4,6]])  #ndim=1
print(vector.ndim)
print(vector.shape) #to know the shape of matrix

0
1
2
torch.Size([2, 2])


# to generate random number

In [7]:
a=torch.rand(size=(3,4))  #to generate random uniform number
print(a)
b=torch.randn(3,4)
print(a)
a=torch.rand(2,3,4) #so 2 different matrixes of size 3*4
print(a)

tensor([[0.3892, 0.4894, 0.7315, 0.8282],
        [0.1136, 0.1603, 0.9173, 0.4244],
        [0.8561, 0.4415, 0.2626, 0.8621]])
tensor([[0.3892, 0.4894, 0.7315, 0.8282],
        [0.1136, 0.1603, 0.9173, 0.4244],
        [0.8561, 0.4415, 0.2626, 0.8621]])
tensor([[[0.2541, 0.2733, 0.9667, 0.6467],
         [0.4895, 0.3373, 0.9565, 0.0638],
         [0.5953, 0.1270, 0.4142, 0.0663]],

        [[0.7361, 0.3279, 0.0458, 0.0808],
         [0.7941, 0.7868, 0.8600, 0.3492],
         [0.4367, 0.5535, 0.8550, 0.8929]]])


# to know the datatype and shape


In [12]:
#to know the datatypes
a=torch.rand(3,4)
print(a)
print(a.dtype)
# assign data type
a=torch.tensor([1.0,2.0,3.0], dtype=torch.int32)
a=torch.tensor([1,2,3], dtype=torch.float64)
a=torch.arange(3,8,dtype=torch.float32)
print(a)
print(a.dtype)
a=a.type(torch.float64)  #to change the datatype of a variable
print(a.dtype)
a=torch.rand(3,4)
print(a.shape)
a=a.T   #to do transpose
print(a.shape)

tensor([[0.4892, 0.5426, 0.9452, 0.3741],
        [0.9541, 0.1483, 0.3216, 0.8482],
        [0.6040, 0.0600, 0.3321, 0.1973]])
torch.float32
tensor([3., 4., 5., 6., 7.])
torch.float32
torch.float64
torch.Size([3, 4])
torch.Size([4, 3])


# mathematical operation

In [ ]:
x = torch.rand(2,2)
x
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3


In [ ]:
#element wise operation
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

In [13]:
#matrix multiplication
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)
# matrix multiplcation
torch.matmul(f, g)

tensor([[2, 0, 3],
        [3, 4, 3]])
tensor([[0, 5],
        [6, 2],
        [4, 7]])


tensor([[12, 31],
        [36, 44]])

In [14]:
#dot product
#torch.dot computes the dot product of two 1-dimensional tensors
#torch.matmul: 1D x 1D: If both tensors are 1D, it behaves exactly like torch.dot, returning a scalar.
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

#special function

In [20]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(k)
# log
print(torch.log(k))
# exp
print(torch.exp(k))
# sigmoid
print(torch.sigmoid(k))
# softmax
print(torch.softmax(k, dim=1))  #apply softmax columnwise
print(k.relu_())

tensor([[7., 7., 9.],
        [0., 0., 0.]])
tensor([[1.9459, 1.9459, 2.1972],
        [  -inf,   -inf,   -inf]])
tensor([[1.0966e+03, 1.0966e+03, 8.1031e+03],
        [1.0000e+00, 1.0000e+00, 1.0000e+00]])
tensor([[0.9991, 0.9991, 0.9999],
        [0.5000, 0.5000, 0.5000]])
tensor([[0.1065, 0.1065, 0.7870],
        [0.3333, 0.3333, 0.3333]])
tensor([[7., 7., 9.],
        [0., 0., 0.]])


# dataloader

In [29]:
import torch
from torch.utils.data import DataLoader
import torchvision
from torchvision import transforms


# 1. Define Transformations

transform = transforms.Compose([
    transforms.Resize((64, 64)),        # Resize image to 64x64
    transforms.ToTensor(),              # Convert PIL Image to tensor (C, H, W) in [0,1]
    transforms.Normalize((0.5,), (0.5,))  # Normalize with mean=0.5, std=0.5
])


# 2. Load Dataset

# Here we use MNIST for simplicity
train_dataset = torchvision.datasets.MNIST(
    root='./data', train=True, download=True, transform=transform
)


# 3. Create DataLoader

train_loader = DataLoader(train_dataset, batch_size=3, shuffle=True)


# 4. Iterate Over Data

for images, labels in train_loader:
    print("Original shape:", images.shape)  # (batch_size, channels, height, width)


    # 5. Tensor Manipulation

    # Indexing: get first image in batch
    first_image = images[0]
    print("First image shape:", first_image.shape)  # (channels, height, width)

    # Reshaping: flatten the image
    flattened = first_image.view(-1)  # shape: (channels*height*width,)
    print("Flattened shape:", flattened.shape)

    # Change shape to (height, width, channels) for some libs (like matplotlib)
    hwc_image = first_image.permute(1, 2, 0)  # (H, W, C)
    print("HWC shape:", hwc_image.shape)

    break  # Just show first batch for demo


Original shape: torch.Size([3, 1, 64, 64])
First image shape: torch.Size([1, 64, 64])
Flattened shape: torch.Size([4096])
HWC shape: torch.Size([64, 64, 1])
