In [4]:
import numpy as np
print("Hello Python , Lets Practice Num Py")

Hello Python , Lets Practice Num Py


In [15]:
oneD = np.array([1,2,3,4,5])
print(oneD)

twoD =np.array([[1,2,3] ,[4,5,6]])
print(twoD)

threeD=np.array(
    [[[1,2,3] ,[4,5,6]] ,[[7,8,9] ,[10,11,12]]]
)
print(threeD)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
oneD.ndim
twoD.ndim
threeD.ndim
oneD.shape
twoD.shape
threeD.shape

(2, 2, 3)

In [30]:
oneD.dtype
threeD.size
#print(oneD[3:])
print(twoD[1,1:])

[5 6]


In [32]:
twoD[:,1]

array([2, 5])