In [22]:
import numpy as np

a = np.array([[2,3],[1,2],[4,5],[7,8]])
print(a.shape)
print(a.sum())
print(a.sum(axis =0))
print(a.sum(axis =1))

(4, 2)
32
[14 18]
[ 5  3  9 15]


In [16]:
import time as time
import numpy as np

n =10
sum =0

for i in range(11):
    for j in range(11):
        sum= sum+i+j

print(sum)

k= np.random.rand(10,10)
print(k)
k.shape

1210
[[0.66104841 0.50290191 0.36028621 0.58703436 0.41980873 0.55724133
  0.19566878 0.96452009 0.37296457 0.85648537]
 [0.37240391 0.61747059 0.04118779 0.63937763 0.76829705 0.23231827
  0.84089301 0.76327129 0.63025721 0.88039719]
 [0.23414245 0.31633192 0.97427055 0.84970545 0.47469169 0.17719482
  0.32091177 0.33759952 0.21158718 0.34949959]
 [0.78693224 0.83448552 0.092173   0.70934182 0.06526497 0.79751286
  0.49550549 0.27161219 0.21738624 0.13258154]
 [0.26681514 0.28758394 0.1641852  0.60607392 0.22723702 0.23545588
  0.30128282 0.13278788 0.17334578 0.62362187]
 [0.97654138 0.63257914 0.16625663 0.67024769 0.73936679 0.28110316
  0.52626286 0.3769874  0.84372914 0.60789617]
 [0.40254172 0.86972431 0.31892762 0.63698365 0.20074843 0.49272166
  0.12141143 0.4117784  0.28243353 0.72178242]
 [0.57125788 0.9776268  0.11297918 0.2667123  0.77766611 0.9911605
  0.26264884 0.58078141 0.17760311 0.61377121]
 [0.76134437 0.83529341 0.44753903 0.6786878  0.6761489  0.471856
  0.835919

(10, 10)

In [13]:

listOfInstructors = { "Professors" : [{"name":"Abir","Subject" :"ML","Salary" :"123432"} , {"name":"Vinay" ,"Subject" :"AI","Salary" :"123432"}] , 
                    "TAs" : [{"name":"Ninand","Subject" :"ML","Salary" :"123432"} , {"name":"Vaibhav" ,"Subject" :"AI","Salary" :"123432"}] }

print(listOfInstructors)
firstProfessor = listOfInstructors["Professors"][0]
keyValues = listOfInstructors["Professors"][0].keys

print(listOfInstructors["Professors"][0].keys)
print(listOfInstructors.values)

d = {"name": "Geeks", "topic": "dict", "task": "iterate"}

for val in d.values():
    print(val)

for val in d.keys():
    print(val)


for keys in d:
    print(keys)


for key,value in d.items():
    print({key},{value})

map_keys = map(d.get,d)


for i in map_keys:
    print("last..."+i)

    print(type(d.keys))

{'Professors': [{'name': 'Abir', 'Subject': 'ML', 'Salary': '123432'}, {'name': 'Vinay', 'Subject': 'AI', 'Salary': '123432'}], 'TAs': [{'name': 'Ninand', 'Subject': 'ML', 'Salary': '123432'}, {'name': 'Vaibhav', 'Subject': 'AI', 'Salary': '123432'}]}
<built-in method keys of dict object at 0x113b17b40>
<built-in method values of dict object at 0x113b0f4c0>
Geeks
dict
iterate
name
topic
task
name
topic
task
{'name'} {'Geeks'}
{'topic'} {'dict'}
{'task'} {'iterate'}
last...Geeks
<class 'builtin_function_or_method'>
last...dict
<class 'builtin_function_or_method'>
last...iterate
<class 'builtin_function_or_method'>


In [15]:
for i in 'String':
    print(i)

for k in ['Rahul Dravid']:
    print(k)

S
t
r
i
n
g
Rahul Dravid


In [21]:
def isEven(num):
    if(num%2==0):
        print(num ," is Even Number")
    else:
        print(num ," is Odd Number")


isEven(10)
isEven(7)
isEven(102)


10  is Even Number
7  is Odd Number
102  is Even Number


In [35]:
import numpy as np

array1= np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

print(array1.shape)
print(array1.sum(axis=0))
print(array1.ndim)
print(array1.size)
print(array1.dtype)
print(array1.nbytes)
print(array1[1][3])
print(array1[1,1])
print(array1[:,1])
print(array1[0,:])






(2, 6)
[ 8 10 12 14 16 18]
2
12
int64
96
10
8
[2 8]
[1 2 3 4 5 6]
